[theme]
base = "light"

# Primary accent color.
primaryColor = "#FF5C8A"
# Background color of the app.
backgroundColor = "#F4FDEB"

# Background color used for most interactive widgets.
secondaryBackgroundColor = "#FFD6E7"

# Color used for almost all text.
textColor = "#2F3A2F"